### ISSUE TITLE
Incorrect size?

### ISSUE THREAD

**Issue by Potherca** [sigmonsays/smallest-docker-httpd#2]
Not that it isn't still super impressive but when I look at `docker images` I see

```
httpd               latest              ba876724d618        19 minutes ago      4.82kB
```

Doesn't that mean the docker image is 4820 bytes? Rather than 436? Or am I missing something super obvious here?

**Comment by sigmonsays** [comment]
it was a while ago when I compiled this and I believe I was on 32bit

i'm not sure what has changed since then in the assemble. Also I assume switching to 64 bit increased the size.

I updated the main readme indicating the new size.
